language: generic
sudo: required

services:
  - docker

before_install: 
  - docker build -t rajatchauhan407/react-client -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true rajatchauhan407/react-client npm test
after_success:
  - docker build -t rajatchauhan407/client ./client
  - docker build -t rajatchauhan407/nginx ./nginx
  - docker build -t rajatchauhan407/server ./server
  - docker build -t rajatchauhan407/worker ./worker

#Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rajatchauhan407/client
  - docker push rajatchauhan407/nginx
  - docker push rajatchauhan407/server
  - docker push rajatchauhan407/worker


