sudo: required

services:
  - docker

before_install: 
  - docker build -t rajatchauhan407/react-test -f Dockerfile.dev ./client

script: 
  - docker run -e CI=true rajatchauhan407/react-test npm test -- --coverage
after_success:
  - docker build -t rajatchauhan407/mulit-client ./client


